learning_platform/course/urls.py
from django.urls import path, include

import course.views as course

app_name = 'course'

urlpatterns = [
    path("", course.CoursesFlowsListView.as_view(), name="index"),
    path("all_courses/", course.CoursesListView.as_view(), name="all_courses"),
    path("all_courses/<int:pk>/", course.CourseDetailView.as_view(), name="course_detail"),

    path("courses/<int:pk>/", course.CourseFlowsDetailView.as_view(), name="course_flow_detail"),
    path("courses/create/", course.CourseCreateView.as_view(), name="course_create"),
    path("courses/<int:pk>/update/", course.CourseUpdateView.as_view(), name="course_update"),
    path("courses/<int:pk>/delete", course.CourseDeleteView.as_view(), name="course_delete"),

    path("flows/", course.CoursesFlowsListView.as_view(), name="all_flows"),
    path("flows/create/", course.CourseFlowsCreateView.as_view(), name="create_flow"),
    path("flows/<int:pk>/update", course.CourseFlowsUpdateView.as_view(), name="flow_update"),
    path("flows/<int:pk>/delete", course.CourseFlowsDeleteView.as_view(), name="flow_delete"),

    path("courses/<int:pk>/lectures/", course.LectureListView.as_view(), name="lectures"),
    path("lectures/<int:pk>", course.LectureDetailView.as_view(),
         name="lectures_detail"),
    path("lectures/<int:pk>/update/", course.LectureUpdateView.as_view(), name="lecture_update"),
    path("lectures/<int:pk>/delete", course.LectureDeleteView.as_view(), name="lecture_delete"),

    path("courses/<int:pk>/timetable/", course.FlowTimetableListView.as_view(), name="timetable"),
    path("timetable/<int:pk>/", course.LectureTimetableDetailView.as_view(), name="timetable_detail"),
    path("timetable/<int:pk>/update/", course.LectureTimetableUpdateView.as_view(),
         name="timetable_update"),
    path("timetable/<int:pk>/delete/", course.LectureTimetableDeleteView.as_view(),
         name="timetable_delete"),

    path("courses/<int:pk>/homework/", course.HomeworkListView.as_view(), name="homework"),
    path("homework/<int:pk>/", course.HomeworkDetailView.as_view(), name="homework_detail"),
    path("homework/<int:pk>/update/", course.HomeworkUpdateView.as_view(), name="homework_update"),
    path("homework/<int:pk>/delete/", course.HomeworkDeleteView.as_view(), name="homework_delete"),

    path("my_homework/<int:pk>/", course.StudentHomeworkDetailView.as_view(), name="my_homework_detail"),
    path("my_homework/<int:pk>/update/", course.StudentHomeworkSendView.as_view(), name="send_homework"),
    path("homework_for_review/<int:pk>/", course.StudentsHomeworkListView.as_view(), name="homework_review"),
]

learning_platform/learning_platform/urls.py
"""learning_platform URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('', include('course.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('users/', include('my_user.urls', namespace='users')),
    path('about/', include('site_data.urls', namespace="about")),
    path('api/', include('course_api.urls', namespace='course_api')),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
                       )

learning_platform/my_user/urls.py
from django.urls import path, re_path

import my_user.views as my_user
from course.views import StudentsHomeworkListView


app_name = "my_user"

urlpatterns = [
    path("login/", my_user.login, name="login"),
    path("logout/", my_user.logout, name="logout"),
    path("register/", my_user.SignUp.as_view(), name="register"),
    path("profile/", my_user.Profile.as_view(), name="profile"),

    path("profile/my_courses/<int:pk>/", StudentsHomeworkListView.as_view(), name="my_course_homework"),
]

learning_platform/my_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core import validators
from django.utils.translation import ugettext_lazy as _


class PhoneValidator(validators.RegexValidator):
    """Checks if phone_number consists of 10 digits and starts with 9 in format 9xxxxxxxxx"""
    regex = r'^9\d{9}$'
    message = "Enter a valid mobile phone number without country code or +. Phone number must contain 10 digits and " \
              "be entered in the format 9xxxxxxxxx"

    flags = 0


class MyUserManager(BaseUserManager):
    """Define a model manager for User without username"""
    use_in_migrations = True

    def _create_user(self, phone_number, password, **extra_fields):
        if not phone_number:
            raise ValueError("Phone number is required")
        user = self.model(phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone_number, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(phone_number, password, **extra_fields)

    def create_superuser(self, phone_number, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(phone_number, password, **extra_fields)



class MyUser(AbstractUser):
    """This class represents Users, authentication via phone_number. Is_student is a flag shown if User is student
    at any Course. is_stuff = True provide access to admin panel. """
    phone_validator = PhoneValidator()
    phone_number = models.CharField(max_length=10,
                                    unique=True,
                                    verbose_name="Номер телефона",
                                    help_text="Field required. Enter a valid number without country code or +",
                                    validators=[phone_validator],
                                    error_messages={"unique": "A user with this phone number already exists"},
                                    )

    username = None
    is_teacher = models.BooleanField(default=False, verbose_name='Является ли преподавателем')
    is_student = models.BooleanField(default=False, verbose_name='Является ли студентом')
    date_of_birth = models.DateField(verbose_name='Дата рождения', blank=True, null=True)
    email = models.EmailField(verbose_name='Email')

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []
    objects = MyUserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        self.full_name = self.get_full_name()
        return self.full_name

learning_platform/my_user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import MyUser


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = MyUser
        fields = "__all__"


class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = MyUser
        fields = "__all__"

learning_platform/my_user/views.py
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import MyUserCreationForm
from course.models import StudentsEnrolled


def login(request):
    login_form = AuthenticationForm(data=request.POST or None)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('course:index'))

    context = {
        'title': 'вход',
        'login_form': login_form,
    }

    return render(request, 'my_user/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('course:index'))


class SignUp(generic.CreateView):
    form_class = MyUserCreationForm
    success_url = reverse_lazy('my_user:login')
    template_name = "my_user/register.html"


class Profile(generic.base.TemplateView):
    template_name = "my_user/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students_courses'] = StudentsEnrolled.objects.filter(student=self.request.user.pk)
        return context

learning_platform/my_user/templates/my_user/base.html
{% extends 'root.html' %}
{% load static %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock%}

learning_platform/my_user/templates/my_user/login.html
{% extends 'my_user/base.html' %}
{% load static %}

{% block title%} {{ title|title }} {% endblock %}

{% block content %}
    <div class="h2">
        Вход в систему
    </div>
    <form method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input type="submit" value="войти">
    </form>
    <button>
        <a href="{% url 'users:register' %}">
            зарегистрироваться
        </a>
    </button>
{% endblock %}

learning_platform/my_user/templates/my_user/profile.html
{% extends "my_user/base.html" %}
{% load static %}

{% block header_title %} <h2>Личный кабинет</h2> {% endblock %}

{% block content %}
<div>
    {% if user.is_teacher %}
    <h4>Преподавательская</h4>
    <hr>
    <h6><a href="{% url 'course:homework_review' pk=1 %}">Задания на проверку</a></h6>
    {% endif %}

    <br>
    <br>
    <br>
    {% if user.is_student %}
    <h4>Мои курсы</h4>
    <hr>
    <h6>Вы записаны на следующие курсы:</h6>
    {% if students_courses|length > 0 %}
    {% for course in students_courses %}
    {{ course.course_flow }}
    <div><a href="{% url 'course:timetable' course.course_flow.pk %}">Расписание занятий</a></div>
    <div><a href="{% url 'my_user:my_course_homework' course.course_flow.pk %}">Домашние задания</a></div>
    <br>
    {% endfor %}
    {% else %}
    <div>Вы не записаны ни на один курс</div>
    {% endif %}
    {% endif %}
    <br>
    <br>
    <br>

    {% if user.is_staff %}
    <h4>Управление содержимым</h4>
    <br>
    <h6>Управление курсами</h6>
    <h6><a href="{% url 'course:all_courses' %}">Редактировать курсы</a></h6>
    <h6><a href="{% url 'course:course_create' %}">Добавить новый курс</a></h6>
    <br>
    <h6>Наборы групп</h6>
    <h6><a href="{% url 'course:all_flows' %}">Редактировать потоки</a> </h6>
    <h6><a href="{% url 'course:create_flow' %}">Добавить поток</a> </h6>
    <br>
    {% endif %}

</div>

{% endblock %}

learning_platform/my_user/templates/my_user/register.html
{% extends 'my_user/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col"><h2>Регистрация нового пользователя</h2></div>
    <div class="col"></div>
</div>

<div class="row">
    <div class="col"></div>
    <div class="col">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Зарегистрироваться">
        </form>
    </div>
    <div class="col"></div>
</div>


{% endblock %}