learning_platform/course/urls.py
from django.urls import path, include

import course.views as course

app_name = 'course'

urlpatterns = [
    path("", course.CoursesFlowsListView.as_view(), name="index"),
    path("all_courses/", course.CoursesListView.as_view(), name="all_courses"),
    path("all_courses/<int:pk>/", course.CourseDetailView.as_view(), name="course_detail"),

    path("courses/<int:pk>/", course.CourseFlowsDetailView.as_view(), name="course_flow_detail"),
    path("courses/create/", course.CourseCreateView.as_view(), name="course_create"),
    path("courses/<int:pk>/update/", course.CourseUpdateView.as_view(), name="course_update"),
    path("courses/<int:pk>/delete", course.CourseDeleteView.as_view(), name="course_delete"),

    path("flows/", course.CoursesFlowsListView.as_view(), name="all_flows"),
    path("flows/create/", course.CourseFlowsCreateView.as_view(), name="create_flow"),
    path("flows/<int:pk>/update", course.CourseFlowsUpdateView.as_view(), name="flow_update"),
    path("flows/<int:pk>/delete", course.CourseFlowsDeleteView.as_view(), name="flow_delete"),

    path("courses/<int:pk>/lectures/", course.LectureListView.as_view(), name="lectures"),
    path("lectures/<int:pk>", course.LectureDetailView.as_view(),
         name="lectures_detail"),
    path("lectures/<int:pk>/update/", course.LectureUpdateView.as_view(), name="lecture_update"),
    path("lectures/<int:pk>/delete", course.LectureDeleteView.as_view(), name="lecture_delete"),

    path("courses/<int:pk>/timetable/", course.FlowTimetableListView.as_view(), name="timetable"),
    path("timetable/<int:pk>/", course.LectureTimetableDetailView.as_view(), name="timetable_detail"),
    path("timetable/<int:pk>/update/", course.LectureTimetableUpdateView.as_view(),
         name="timetable_update"),
    path("timetable/<int:pk>/delete/", course.LectureTimetableDeleteView.as_view(),
         name="timetable_delete"),

    path("courses/<int:pk>/homework/", course.HomeworkListView.as_view(), name="homework"),
    path("homework/<int:pk>/", course.HomeworkDetailView.as_view(), name="homework_detail"),
    path("homework/<int:pk>/update/", course.HomeworkUpdateView.as_view(), name="homework_update"),
    path("homework/<int:pk>/delete/", course.HomeworkDeleteView.as_view(), name="homework_delete"),

    path("my_homework/<int:pk>/", course.StudentHomeworkDetailView.as_view(), name="my_homework_detail"),
    path("my_homework/<int:pk>/update/", course.StudentHomeworkSendView.as_view(), name="send_homework"),
    path("homework_for_review/<int:pk>/", course.StudentsHomeworkListView.as_view(), name="homework_review"),
]

learning_platform/learning_platform/urls.py
"""learning_platform URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('', include('course.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('users/', include('my_user.urls', namespace='users')),
    path('about/', include('site_data.urls', namespace="about")),
    path('api/', include('course_api.urls', namespace='course_api')),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
                       )

learning_platform/course/models.py
from django.db import models
from django.utils.text import slugify

from my_user.models import MyUser


class CourseCategory(models.Model):
    """This models represents Course Categories, showing in main menu (like Programming, Marketing, DevOps, etc)"""
    title = models.CharField(max_length=70, unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Слег')
    is_active = models.BooleanField(default=False, verbose_name='Активная категория')

    class Meta:
        verbose_name = 'Категори'
        verbose_name_plural = 'Категории'
        ordering = ["title"]

    def __str__(self):
        return self.title


class Course(models.Model):
    """This models represents information about Courses. Unactive course is not shown at the web-site but can be used
    to get some statistic data in reports.
    Each course has a version (integer: 1,2,3, etc) Please add a new version in case of serious modifications of
    course (like price changing).
    Course duration is a sting in format: "4 месяца, 4 академ. часа в неделю Пн 20:00, Чт 20:00".
    Each launch of course in represented in class CourseFlows. """
    title = models.CharField(max_length=70, blank=False, verbose_name='Наименование курса')
    slug = models.SlugField(max_length=200, verbose_name='Слег')
    is_active = models.BooleanField(default=False, verbose_name='Курс доступен')
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE, related_name='categories',
                                 verbose_name='Категория')
    short_description = models.CharField(max_length=300, verbose_name='Краткое описание')
    overview = models.TextField(verbose_name='Описание')
    duration = models.CharField(max_length=100, verbose_name='Продолжительность')
    price = models.IntegerField(verbose_name='Цена')
    creation_date = models.DateField(auto_now_add=True)
    version = models.IntegerField(verbose_name='Версия курса')


    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['title']

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title} версия {self.version}'


class CourseLecture(models.Model):
    """This class represents Lectures, that should be given in course. This models contains general information
    about lecture such as title, sequence_number in study plan, info (description, goals, etc), version.
    Each lecture should be attached to specific version of course.
    Specific data like tutor, date will be provided in CourseFlowTimetable."""
    title = models.CharField(max_length=100, blank=False, verbose_name='Тема занятия')
    sequence_number = models.IntegerField(verbose_name='Порядковый Номер занятия в курсе')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='syllabus',
                               verbose_name='Курс')
    description = models.TextField(verbose_name='Описание занятия')
    is_active = models.BooleanField(verbose_name='Доступность', default=False)
    version = models.IntegerField(verbose_name='Версия урока', default=1)

    class Meta:
        verbose_name = 'Учебный план курса'
        verbose_name_plural = 'Учебные планы курсов'
        ordering = ['title']

    def __str__(self):
        return f'"{self.title}" курса "{self.course}"'


class CourseFlows(models.Model):
    """This class represents each launch of course. Course code is should have a abbreviation of course subject and
    start date (like, PHP 10.2019) """
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_flows', verbose_name='Курс')
    start_date = models.DateField(blank=False, verbose_name='Дата начала')
    curator = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='course_flows',
                                verbose_name='Куратор')
    code = models.CharField(max_length=50, unique=True, verbose_name='Код потока')
    is_active = models.BooleanField(default=True, verbose_name='Идет обучение')

    class Meta:
        verbose_name = 'Поток (набор) курса'
        verbose_name_plural = 'Потоки курсов'
        ordering = ['start_date']

    def __str__(self):
        return f'{self.course} {self.start_date}'

    def __repr__(self):
        return f'{self.course} {self.start_date}'


class Homework(models.Model):
    """This class represents homework, that should be done during each course flow. """
    title = models.CharField(verbose_name='Название', max_length=200, blank=False)
    sequence_number = models.IntegerField(verbose_name='Порядковый номер в курсе', default=1)
    course_flow = models.ForeignKey(CourseFlows, on_delete=models.CASCADE, related_name='homework',
                                    verbose_name='Поток курса')
    description = models.TextField(verbose_name='Описание')
    due_date = models.DateField(verbose_name='Срок сдачи')
    is_active = models.BooleanField(verbose_name='Доступность', default=False)

    class Meta:
        verbose_name = 'Домашнее задание'
        verbose_name_plural = 'Домашние задания'

    def __str__(self):
        return f'№{self.sequence_number} {self.title} {self.course_flow}'


class StudentsEnrolled(models.Model):
    """This class represents Students enrolled in each Course Flow"""
    course_flow = models.ForeignKey(CourseFlows, on_delete=models.CASCADE, related_name='students_in_flow',
                                    verbose_name='Поток курса')
    student = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='students_in_flow',
                                verbose_name='Студент')
    start_learning_date = models.DateField(verbose_name='Дата начала обучения')
    is_active = models.BooleanField(default=True, verbose_name='Учится')

    class Meta:
        verbose_name = 'Студенты в потоке'
        verbose_name_plural = 'Студенты в потоке'

    def __str__(self):
        return f'{self.student} {self.course_flow}'


class StudentsHomework(models.Model):
    """This course represents information about each Student's academic performance.  """
    HOMEWORK_STATUS_NOT_DONE = 0
    HOMEWORK_STATUS_ON_REVIEW = 1
    HOMEWORK_STATUS_SEND_TO_REWORK = 2
    HOMEWORK_STATUS_COMPLETE = 3
    HOMEWORK_STATUS_CHOICES = ((HOMEWORK_STATUS_NOT_DONE, "Не сдано"),
                               (HOMEWORK_STATUS_ON_REVIEW, "На проверке"),
                               (HOMEWORK_STATUS_SEND_TO_REWORK, "Отправлено на доработку"),
                               (HOMEWORK_STATUS_COMPLETE, "Сдано")
                               )


    course_flow = models.ForeignKey(CourseFlows, on_delete=models.CASCADE, related_name='students_homework',
                                    verbose_name='Поток курса')
    student = models.ForeignKey(StudentsEnrolled, on_delete=models.CASCADE, related_name='students_homework',
                                verbose_name='Студент')
    homework = models.ForeignKey(Homework, on_delete=models.CASCADE, related_name='students_homework',
                                 verbose_name='Дом задание')
    date_of_completion = models.DateField(blank=True, null=True, verbose_name='Факт дата сдачи')
    content = models.TextField(max_length=300, default='Прикрепите ссылку на репозиторий',
                               blank=True, verbose_name='Содержание')
    status = models.PositiveSmallIntegerField(choices=HOMEWORK_STATUS_CHOICES, default=HOMEWORK_STATUS_NOT_DONE,
                                              verbose_name='Статус работы')
    teacher_comments = models.TextField(blank=True, verbose_name='Комментарии преподавателя')

    class Meta:
        verbose_name = 'Успеваемость студентов'
        verbose_name_plural = 'Успеваемость студентов'

    def __str__(self):
        return f'Домашняя работа "{self.homework.title}" Student {self.student.student.first_name}'


class CourseFlowTimetable(models.Model):
    """This class represents timetable of each Course Flow."""
    lesson = models.ForeignKey(CourseLecture, on_delete=models.CASCADE, related_name='courseflow_timetable',
                               verbose_name='Номер занятия')
    course_flow = models.ForeignKey(CourseFlows, on_delete=models.CASCADE, related_name='courseflow_timetable',
                                    verbose_name='Поток курса')
    date = models.DateTimeField(verbose_name='Дата занятия')
    teacher = models.ForeignKey(MyUser, on_delete=models.CASCADE, verbose_name='Преподаватель')

    class Meta:
        verbose_name = 'Расписание занятий'
        verbose_name_plural = 'Расписание занятий'

    def __str__(self):
        return f"{self.lesson} {self.date}"

learning_platform/course/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Course, CourseFlows, CourseLecture, Homework, CourseFlowTimetable, StudentsHomework


#Course
class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = "__all__"
        exclude = ['slug']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


#CourseFlows
class CourseFlowsForm(ModelForm):
    class Meta:
        model = CourseFlows
        fields = "__all__"


#Lecures
class CourseLecturesForm(ModelForm):
    class Meta:
        model = CourseLecture
        fields = "__all__"


#LecuresTimetable
class CourseLecturesForm(ModelForm):
    class Meta:
        model = CourseFlowTimetable
        fields = "__all__"


#Homework
class HomeowrkForm(ModelForm):
    class Meta:
        model = Homework
        fields = "__all__"


class StudentHomeowrkForm(ModelForm):
    class Meta:
        model = StudentsHomework
        fields = "__all__"


class StudentHomeworkSendForm(ModelForm):
    disabled_fields = ("course_flow", "student", "homework")

    class Meta:
        model = StudentsHomework
        fields = ("content","course_flow", "student", "homework")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True


class StudentHomeworkCheckForm(ModelForm):
    disabled_fields = ("course_flow", "student", "homework", "content")

    class Meta:
        model = StudentsHomework
        fields = ("content","course_flow", "student", "homework", "teacher_comments", "status")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.disabled_fields:
            self.fields[field].disabled = True

learning_platform/course/templates/course/course_detail.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
    <div class="content">
        <h2>{{ course.title }}</h2>
        <h5>{{ course.category }}</h5>
        <hr>

        <h4>{{ course.short_description }} </h4>
        <p>{{ course.overview }}</p>
        <p>Продолжительность курса {{ course.duration}}</p>
        <p>Цена {{ course.price}}</p>
    </div>
<div>
    <hr>
    <h4>Программа курса</h4>
    <div>Вас ждут онлайн-лекции и офлайн-воркшопы с практикующими специалистами.</div>
    <a href="{% url 'course:lectures' course.pk %}">Учебная программа</a>
</div>

<hr>
        {% if user.is_staff %}
        <div><a href="{% url 'course:course_update' course.pk %}">Редактировать описание </a></div>
        <div><a href="{% url 'course:course_delete' course.pk %}">Удалить курс</a></div>
        {% endif %}

{% endblock %}

learning_platform/course/templates/course/course_list.html
{% extends 'course/base.html' %}
{% load static %}

{% block header_title %}
<h2>Наши учебные программы</h2>
<h5>Программы продолжительностью от нескольких недель до 1 года, которые позволяют освоить
    конкретный навык или инструмент и добавить его в свое резюме.</h5>
<hr>
{% endblock %}

{% block content %}
<div>
    {% for course in courses %}
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col-10"><h2> {{course.title}} </h2>

            {% if user.is_staff %}
            <a href="{% url 'course:course_update' course.pk %}">Редактировать </a>
            <a href="{% url 'course:course_delete' course.pk %}">Удалить </a>
            {% endif %}

            <div><h6>Направление: {{ course.category }} </h6></div>
            <div><h6>Продолжительность: {{ course.duration }}</h6></div>
            <p> {{ course.short_description }}
            <a href="{% url 'course:course_detail' pk=course.pk  %}"> Подробнее </a> </p>
            <hr>
        </div>
        <div class="col"></div>
    </div>
    {% endfor %}
</div>

{% if is_paginated %}
    <div class="article-paginator">
        <span class="page-links">
            <a href="{% url 'course:index' %}?page=1"> << </a>
        {% if page_obj.has_previous %}
            <a href="{% url 'course:index' %}?={{ page_obj.previous_page_number }}"> < </a>
        {% endif %}
        <span class="current-page">
            страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="{% url 'course:index' %}?page={{ page_obj.next_page_number }}"> < </a>
        {% endif %}
            <a href="{% url 'course:index' %}?page={{ page_obj.paginator.num_pages }}"> > </a>
        </span>
    </div>
    {% endif %}
{% endblock %}

learning_platform/course/templates/course/courseflows_confirm_delete.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="course-delete_confirm">
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="удалить курс {{ course.title }}?">
    </form>
    <button>
        <a href="{% url 'course:index' %}">Отмена</a>
    </button>
</div>

{% endblock %}

learning_platform/course/templates/course/courseflows_detail.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
    <div class="content">
        <h2> Курс {{ courseflows.course.title }}</h2>
        <h6>{{ courseflows.course.category }}</h6>
        <h5>{{ courseflows.course.short_description }} </h5>
        <hr>
        <h6>Продолжительность курса  {{ courseflows.course.duration}}</h6>
        <h6> Начало занятий {{ courseflows.start_date }}</h6>
        <hr>
        <p>{{ courseflows.course.overview }}</p>

        <h5>Цена {{ courseflows.course.price}}</h5>
        <hr>

        <h3>Расписание занятий</h3>
        <div>Вас ждут онлайн-лекции и офлайн-воркшопы с практикующими специалистам</div>
        <a href="{% url 'course:timetable' courseflows.pk %}">Расписание занятий</a>
        <hr>

        <h3>Домашние задания</h3>
            <a href="{% url 'course:homework' courseflows.pk %}">Посмотреть</a>

        <hr>


        {% if user.is_staff %}
        <div><a href="{% url 'course:flow_update' courseflows.pk %}">редактировать</a> </div>
        <div><a href="{% url 'course:flow_delete' courseflows.pk %}">Удалить </a></div>

        {% endif %}
    </div>

{% endblock %}

learning_platform/course/templates/course/courseflowtimetable_confirm_delete.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="course-delete_confirm">
    <form method="post">
        {% csrf_token %}
        <input type="submit"
               value="удалить занятие {{ courseflowtimetable.lesson.title }} из расписания?">
    </form>
    <button>
        <a href="{% url 'course:index' %}">Отмена</a>
    </button>
</div>

{% endblock %}

learning_platform/course/templates/course/courseflowtimetable_form.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}

<div class="col-md-offset-3 col-md-6">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="сохранить">
    </form>
</div>

{% endblock %}

learning_platform/course/templates/course/courselecture_confirm_delete.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="course-delete_confirm">
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="удалить занятие {{ courselecture.title }}?">
    </form>
    <button>
        <a href="{% url 'course:index' %}">Отмена</a>
    </button>
</div>

{% endblock %}

learning_platform/course/templates/course/courselecture_detail.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
    <div class="content">
        <h2> {{ courselecture.title }}</h2>
        <div>
            <span>Занятие №{{ courselecture.sequence_number}}</span>
            <span>Курса {{ courselecture.course.title }}</span>
        </div>
        <hr>
        <div>{{ courselecture.description }}</div>
        <hr>


        {% if user.is_staff %}
        <div><a href="{% url 'course:lecture_update' courselecture.pk %}">редактировать</a> </div>
        <div><a href="{% url 'course:lecture_delete' courselecture.pk %}">Удалить </a></div>

        {% endif %}
    </div>

{% endblock %}

learning_platform/course/templates/course/courselecture_form.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}

<div class="col-md-offset-3 col-md-6">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="сохранить">
    </form>
</div>

{% endblock %}

learning_platform/course/templates/course/courselecture_list.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
<div class="row">
    <div class="col"></div>
    <div class="col-10"><h2>Учебная программа курса</h2></div>
    <div class="col"></div>
</div>
<div>
    {% for lecture in lectures %}
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col-10"><h2> Занятие {{lecture.sequence_number}} </h2>

            {% if user.is_staff %}
            {% endif %}
            <h6>{{ lecture.title }}</h6>
            <a href="{% url 'course:lectures_detail' pk=lecture.pk  %}"> Подробнее </a> </p>

        </div>
        <div class="col"></div>
    </div>
    {% endfor %}
</div>

{% if is_paginated %}
    <div class="article-paginator">
        <span class="page-links">
            <a href="{% url 'course:index' %}?page=1"> << </a>
        {% if page_obj.has_previous %}
            <a href="{% url 'course:index' %}?={{ page_obj.previous_page_number }}"> < </a>
        {% endif %}
        <span class="current-page">
            страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="{% url 'course:index' %}?page={{ page_obj.next_page_number }}"> < </a>
        {% endif %}
            <a href="{% url 'course:index' %}?page={{ page_obj.paginator.num_pages }}"> > </a>
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

learning_platform/course/templates/course/homework_detail.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
    <div class="content">
        <h5> Курс {{ homework.course_flow.course }}</h5>
        <h3>Домашнее задание № {{ homework.sequence_number }}</h3>
        <h4>{{ homework.title }}</h4>
        <hr>
        <h6>Описание задания</h6>
        <h7>{{ homework.description }}</h7>
        <hr>
        <h6>Необходимо сдать до {{ homework.due_date }}</h6>

        {% if user.is_staff %}
        <div><a href="{% url 'course:homework_update' homework.pk %}">редактировать</a> </div>
        <div><a href="{% url 'course:homework_delete' homework.pk %}">Удалить </a></div>
        {% endif %}

        {% if user.is_student %}
        <div>Отправить задание на проверку</div>
        {% endif%}
    </div>

{% endblock %}

learning_platform/course/templates/course/homework_list.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-offset-3">
<div class="row">
    <div class="col"></div>
    <div class="col-10"><h2>Домашние задания</h2></div>
    <div class="col"></div>
</div>
<div>
    {% for homework in homeworks %}
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col-10"><h4> №{{homework.sequence_number}} {{homework.title}} </h4>
            <a href="{% url 'course:homework_detail' homework.pk %}">Подробнее</a>
            {% if user.is_staff %}

            {% endif %}
            <h6>{{ homework.description }}</h6>
            <hr>

        </div>
        <div class="col"></div>
    </div>
    {% endfor %}
</div>

{% if is_paginated %}
    <div class="article-paginator">
        <span class="page-links">
            <a href="{% url 'course:index' %}?page=1"> << </a>
        {% if page_obj.has_previous %}
            <a href="{% url 'course:index' %}?={{ page_obj.previous_page_number }}"> < </a>
        {% endif %}
        <span class="current-page">
            страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="{% url 'course:index' %}?page={{ page_obj.next_page_number }}"> < </a>
        {% endif %}
            <a href="{% url 'course:index' %}?page={{ page_obj.paginator.num_pages }}"> > </a>
        </span>
    </div>
    {% endif %}
</div>
{% endblock %}

learning_platform/course/templates/course/studentshomework_form.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}

<div class="col-md-offset-3 col-md-6">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="сохранить">
    </form>
</div>

{% endblock %}

learning_platform/course/templates/course/studentshomework_list.html
{% extends 'course/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-offset-3">
<div class="row">
    <div class="col"></div>
    <div class="col-10"><h2>Домашние задания</h2></div>
    <div class="col"></div>
</div>
<div>
    {% if user.is_teacher %}
    {% for homework in homeworks.teacher %}
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col-10"><h4> №{{homework.homework.sequence_number}} {{homework.homework.title}} </h4>
            <h6>Статус: {{ homework.get_status_display }}</h6>
            <a href="{% url 'course:my_homework_detail' homework.pk %}">Подробнее</a>
            <hr>
        </div>
        <div class="col"></div>
    </div>
    {% endfor %}
    {% endif %}

    <hr>
    <div>Раздел студента</div>
    {% if user.is_student %}
    {% for homework in homeworks.student %}
    <div class="row align-items-center">
        <div class="col"></div>
        <div class="col-10"><h4> №{{homework.homework.sequence_number}} {{homework.homework.title}} </h4>
            <h6>Статус: {{ homework.get_status_display }}</h6>
            <a href="{% url 'course:my_homework_detail' homework.pk %}">Подробнее</a>
            <hr>
        </div>
        <div class="col"></div>
    </div>
    {% endfor %}
    {% endif %}
</div>


</div>
{% endblock %}