learning_platform/course/urls.py
from django.urls import path, include

import course.views as course

app_name = 'course'

urlpatterns = [
    path("", course.CoursesFlowsListView.as_view(), name="index"),
    path("all_courses/", course.CoursesListView.as_view(), name="all_courses"),
    path("all_courses/<int:pk>/", course.CourseDetailView.as_view(), name="course_detail"),

    path("courses/<int:pk>/", course.CourseFlowsDetailView.as_view(), name="course_flow_detail"),
    path("courses/create/", course.CourseCreateView.as_view(), name="course_create"),
    path("courses/<int:pk>/update/", course.CourseUpdateView.as_view(), name="course_update"),
    path("courses/<int:pk>/delete", course.CourseDeleteView.as_view(), name="course_delete"),

    path("flows/", course.CoursesFlowsListView.as_view(), name="all_flows"),
    path("flows/create/", course.CourseFlowsCreateView.as_view(), name="create_flow"),
    path("flows/<int:pk>/update", course.CourseFlowsUpdateView.as_view(), name="flow_update"),
    path("flows/<int:pk>/delete", course.CourseFlowsDeleteView.as_view(), name="flow_delete"),

    path("courses/<int:pk>/lectures/", course.LectureListView.as_view(), name="lectures"),
    path("lectures/<int:pk>", course.LectureDetailView.as_view(),
         name="lectures_detail"),
    path("lectures/<int:pk>/update/", course.LectureUpdateView.as_view(), name="lecture_update"),
    path("lectures/<int:pk>/delete", course.LectureDeleteView.as_view(), name="lecture_delete"),

    path("courses/<int:pk>/timetable/", course.FlowTimetableListView.as_view(), name="timetable"),
    path("timetable/<int:pk>/", course.LectureTimetableDetailView.as_view(), name="timetable_detail"),
    path("timetable/<int:pk>/update/", course.LectureTimetableUpdateView.as_view(),
         name="timetable_update"),
    path("timetable/<int:pk>/delete/", course.LectureTimetableDeleteView.as_view(),
         name="timetable_delete"),

    path("courses/<int:pk>/homework/", course.HomeworkListView.as_view(), name="homework"),
    path("homework/<int:pk>/", course.HomeworkDetailView.as_view(), name="homework_detail"),
    path("homework/<int:pk>/update/", course.HomeworkUpdateView.as_view(), name="homework_update"),
    path("homework/<int:pk>/delete/", course.HomeworkDeleteView.as_view(), name="homework_delete"),

    path("my_homework/<int:pk>/", course.StudentHomeworkDetailView.as_view(), name="my_homework_detail"),
    path("my_homework/<int:pk>/update/", course.StudentHomeworkSendView.as_view(), name="send_homework"),
    path("homework_for_review/<int:pk>/", course.StudentsHomeworkListView.as_view(), name="homework_review"),
]

learning_platform/learning_platform/urls.py
"""learning_platform URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('', include('course.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('users/', include('my_user.urls', namespace='users')),
    path('about/', include('site_data.urls', namespace="about")),
    path('api/', include('course_api.urls', namespace='course_api')),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
                       )

learning_platform/my_user/urls.py
from django.urls import path, re_path

import my_user.views as my_user
from course.views import StudentsHomeworkListView


app_name = "my_user"

urlpatterns = [
    path("login/", my_user.login, name="login"),
    path("logout/", my_user.logout, name="logout"),
    path("register/", my_user.SignUp.as_view(), name="register"),
    path("profile/", my_user.Profile.as_view(), name="profile"),

    path("profile/my_courses/<int:pk>/", StudentsHomeworkListView.as_view(), name="my_course_homework"),
]

learning_platform/site_data/urls.py
from django.urls import path

from .views import ContactUs


app_name = 'site_data'

urlpatterns = [
    path('contact/', ContactUs.as_view(), name='contact'),
]

learning_platform/templates/root.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>
        {% block title %}
        Классные курсы Нельсона
        {% endblock %}
    </title>

    {% block css %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
  </head>

  <body>
    <row class="container">
        <col>
      {% block header %}
      <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="{% url 'course:index' %}">Онлайн университет</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              {% block main_menu %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'course:all_courses' %}">Наши направления
                  </a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'course:all_flows' %}">Выбрать курс
                  </a>
                </li>
              {% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'course:index' %}">О нас</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about:contact' %}">Контакты</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'users:profile' %}" class="nav-link">
                    <span class="glyphicon glyphicon-user"></span>Личный кабинет
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'users:logout' %}" class="nav-link">
                    <span class="glyphicon glyphicon-log-in"></span>Выйти
                  </a>
                </li>
              {% else %}
              <li class="nav-item">
                  <a href="{% url 'users:register' %}" class="nav-link">
                    <span class="glyphicon glyphicon-user"></span>Зарегистироваться
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'users:login' %}" class="nav-link">
                    <span class="glyphicon glyphicon-log-in"></span> Войти
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </header> </col></row>
    {% endblock %}
    <row>

      <div class="container">
        <div class="col-md-offset-3 col-md-12">
          <div class="row .p-4">
            <div class="col"></div>
            <div class="col-10">{% block header_title %}{% endblock%}</div>
            <div class="col"></div>
</div>
      {% block content %}

      {% endblock %}
        </div>
</div>
    </row>
  </div>
  </body>
</html>